name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build binaries
        run: cargo build --target x86_64-unknown-linux-musl --release

      - name: Strip binary
        run: strip target/x86_64-unknown-linux-musl/release/spnhub

      - name: Prepare assets
        run: |
          mkdir -p release-assets
          cp target/x86_64-unknown-linux-musl/release/spnhub release-assets/spnhub
          cat <<EOF > release-assets/Dockerfile
          FROM scratch
          COPY spnhub /spnhub
          ENTRYPOINT ["/spnhub"]
          EOF

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          body: "Automatically built from the latest commit on main branch."
          files: |
            release-assets/spnhub

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: release-assets
          push: true
          tags: ${{ steps.meta.outputs.tags }}
